<?php
/** @package DespensaEsforco::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CompraAutomaticaMap.php");

/**
 * CompraAutomaticaDAO provides object-oriented access to the compra_automatica table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DespensaEsforco::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CompraAutomaticaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $NomeSupermercado;

	/** @var string */
	public $Categoria;

	/** @var string */
	public $Prioridade;

	/** @var int */
	public $ValorMaximo;

	/** @var string */
	public $MetodoPagamento;

	/** @var string */
	public $EnderecoEntrega;



}
?>